name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v2
    - name: Racket Package CI
      uses: jackfirth/racket-package-ci-action@v0.1.4
      with:
        name: otp
        directory: otp
