name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Install package
      uses: docker://racket/racket:7.9-full
      with:
        entrypoint: raco
        args: pkg install --auto otp/ otp-lib/ otp-doc/
    - name: Run tests
      uses: docker://racket/racket:7.9-full
      with:
        entrypoint: raco
        args: test otp otp-lib
    - name: Deploy documentation
      uses: docker://racket/racket:7.9-full
      with:
        entrypoint: ./docs.sh
        doc_directory: otp-doc
        main_ref: refs/heads/master
        scribble_file: otp
        github_token: ${{ secrets.GITHUB_TOKEN }}
